config/routes.rb
SocialThinkamajig::Application.routes.draw do

  resources :users, only: [:new, :create, :edit, :update]

  resource :session, only: [:new, :create, :destroy] do
    post 'reset_password', on: :member
  end

  resources :friend_circles, except: [:index]

  resources :posts

end

app/models/friend_circle.rb
class FriendCircle < ActiveRecord::Base
  attr_accessible :name, :user_id, :friend_ids

  belongs_to(
    :user,
    class_name: "User",
    primary_key: :id,
    foreign_key: :user_id
  )

  has_many  :friend_circle_memberships,
            class_name: "FriendCircleMembership",
            foreign_key: :friend_circle_id,
            primary_key: :id,
            dependent: :destroy

  has_many  :friends,
            through: :friend_circle_memberships,
            source: :friend

  has_many :post_shares,
            class_name: "PostShare",
            primary_key: :id,
            foreign_key: :friend_circle_id

  has_many :posts,
            through: :post_shares,
            source: :post


  def friend_ids=(user_id_arr)
    users = user_id_arr.map do |id|
      User.find(id)
    end
    self.friends = users
  end

  # has many members

  # has many
end

app/models/friend_circle_membership.rb
class FriendCircleMembership < ActiveRecord::Base
  attr_accessible :friend_circle_id, :user_id

  validates   :friend_circle_id, :user_id, presence: true
  validates   :friend_circle_id, uniqueness: { scope: :user_id }

  belongs_to(
    :friend,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )

  belongs_to  :friend_circle,
              class_name: "FriendCircle",
              foreign_key: :friend_circle_id,
              primary_key: :id


end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :post_id, :url

  belongs_to  :post,
              class_name: "Post",
              primary_key: :id,
              foreign_key: :post_id
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :user_id, :friend_circle_ids

  has_many  :links,
            class_name: "Link",
            foreign_key: :post_id,
            primary_key: :id

  has_many :post_shares,
            class_name: "PostShare",
            primary_key: :id,
            foreign_key: :post_id

  has_many :friend_circles,
            through: :post_shares,
            source: :friend_circle

  def friend_circle_ids=(ids)
    self.friend_circles = ids.map do |id|
      FriendCircle.find(id)
    end
  end

end

app/models/post_share.rb
class PostShare < ActiveRecord::Base
  attr_accessible :post_id, :friend_circle_id

  validates :post_id, :friend_circle_id, presence: true
  validates :post_id, uniqueness: { scope: :friend_circle_id }

  belongs_to  :post,
              class_name: 'Post',
              foreign_key: :post_id,
              primary_key: :id

  belongs_to  :friend_circle,
              class_name: 'FriendCircle',
              foreign_key: :friend_circle_id,
              primary_key: :id

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :session_token, :password
  attr_reader :password

  validates :email, presence: true
  validates :password_digest, presence: { message: "Password can't be blank" }
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6 }, allow_nil: true

  before_validation { |user| user.reset_session_token!(false) }

  has_many(
    :owned_friend_circles,
    class_name: "FriendCircle",
    primary_key: :id,
    foreign_key: :user_id
  )

  has_many  :friend_circle_memberships,
            class_name: 'FriendCircleMembership',
            foreign_key: :user_id,
            primary_key: :id,
            dependent: :destroy

  has_many  :member_friend_circles,
            through: :friend_circle_memberships,
            source: :friend_circle


  def reset_session_token!(force = true)
    return unless self.session_token.nil? || force
    self.session_token = SecureRandom::urlsafe_base64(16)
    self.save!
  end

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def set_reset_key!
    key = SecureRandom::urlsafe_base64(16)
    self.reset_key = key
    self.save!
    key
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include ApplicationHelper
end

app/controllers/friend_circles_controller.rb
class FriendCirclesController < ApplicationController
  def new
    render :new
  end

  def create
    friend_circle = FriendCircle.new(params[:friend_circle])

    if friend_circle.save
      redirect_to friend_circle_url(friend_circle)
    else
      redirect_to new_friend_circle_url
    end
  end

  def show
    @friend_circle = FriendCircle.find(params[:id])
    render :show
  end

  def edit
    @friend_circle = FriendCircle.find(params[:id])
    render :edit
  end

  def update
    friend_circle = FriendCircle.find(params[:id])

    if friend_circle.update_attributes(params[:friend_circle])
      redirect_to friend_circle_url(friend_circle)
    else
      redirect_to edit_friend_circle_url
    end
  end

  def destroy
    friend_circle = FriendCircle.find(params[:id])
    friend_circle.destroy!

    redirect_to new_friend_circle_url
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    render :new
  end

  def create
    begin
      ActiveRecord::Base.transaction do
        @post = Post.create(params[:post])
        urls = params[:link][:url]
        #fail
        links = []

        urls.each do |url|
          next if url == ""
          links << Link.create(url: url, post_id: @post.id)
        end

        raise "Something is wrong" unless @post.valid? && links.all? { |link| link.valid? }
      end
    rescue
      fail
      render :new
    else
      redirect_to post_url(@post)
    end
  end

  def show
    @post = Post.find(params[:id])

    render :show
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])

    @post.update_attributes(params[:post])
    # WARNING THIS DOESN'T WORK
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email],
                                      params[:user][:password])
    if @user.nil?
      flash[:error] = 'Invalid email / password' # change other for consistency
      redirect_to new_session_url
    else
      # flash confirmation?
      session[:session_token] = @user.session_token
      redirect_to session_url
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil

    redirect_to root
  end


  def reset_password
    user = User.find_by_email(params[:user][:email])
    ResetMailer.password(user).deliver!

    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_filter make sure user is not already logged in


  def new
    render :new
  end

  def create
    @user = User.new(params[:user])

    if @user.save

      redirect_to session_url
    else
      flash.now[:errors] ||= []
      flash.now[:errors] << @user.errors.full_messages

      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    @key = params[:key]
    if @user.reset_key == params[:key]
      render :edit
    else
      redirect_to new_session_url
    end
  end

  def update
    user = User.find(params[:id])
    user.password = params[:user][:password]
    if user.save
      redirect_to new_session_url
    else
      @user = user

      render :edit
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end
end

app/helpers/friend_circles_helper.rb
module FriendCirclesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friend_circles/_friends.html.erb
<form action="<%= url %>" method="post">

  <% if method == :put %>
    <input type="hidden" name="_method" value="put">
  <% end %>

  <input type="hidden" name="authenticity_token"
          value="<%= form_authenticity_token %>">

  <input type="hidden" name="friend_circle[user_id]"
          value="<%= current_user.id %>">


  <label>
    Name
    <input type="text" name="friend_circle[name]"
            value="<%= friend_circle.name %>">
  </label>


  <% User.all.each do |user| %>
    <br>
    <label>
      <%= user.email %>
      <input type="checkbox" name="friend_circle[friend_ids][]"
              value="<%= user.id %>">
    </label>

  <% end %>

  <br>
  <input type="submit">

</form>

app/views/friend_circles/new.html.erb
<h1>Create Friend Circle</h1>

<form action="<%= friend_circles_url %>" method="post">
  <input type="hidden" name="authenticity_token"
          value="<%= form_authenticity_token %>">

  <input type="hidden" name="friend_circle[user_id]"
          value="<%= current_user.id %>">

  <label>
    Name
    <input type="text" name="friend_circle[name]">
  </label>


  <% User.all.each do |user| %>
    <br>
    <label>
      <%= user.email %>
      <input type="checkbox" name="friend_circle[friend_ids][]"
              value="<%= user.id %>">
    </label>

  <% end %>

  <br>
  <input type="submit">

</form>

app/views/friend_circles/show.html.erb
<h1> !!!FriendCircles!!! </h1>

<h2> <%= @friend_circle.name %> </h2>

<h3> Owner: <%=@friend_circle.user.email %> </h3>


<ul>
<% @friend_circle.friends.each do |friend| %>
  <li><%= friend.email %></li>
<% end %>
</ul>

app/views/layouts/_user.html.erb
<form action="<%= url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>
    Email
    <input type="text" name="user[email]">
  </label>

  <label>
    Password
    <input type="password" name="user[password]">
  </label>

  <input type="submit" name="Create user">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialThinkamajig</title>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_post_form.html.erb
<form action="<%= url %>" method='post'>
    <input type="hidden"
            name="authenticity_token"
            value="<%= form_authenticity_token %>">

    <% if method == :put %>
      <input type="hidden" name="_method" value="put">
    <% end %>

    <input type="hidden" name="post[user_id]" value="<%= current_user.id %>">

    <label>
      Body
      <textarea name="post[body]"><%= post.body %></textarea>
    </label>
    <br>

    <label>
      Link 1
      <input type="text" name="link[url][]"
              value="<%=post.links[0].url if post.links[0]%>">
    </label>
    <br>

    <label>
      Link 2
      <input type="text" name="link[url][]"
              value="<%=post.links[1].url if post.links[1]%>">
    </label>
    <br>
    <label>
      Link 3
      <input type="text" name="link[url][]"
            value="<%=post.links[2].url if post.links[2]%>">
    </label>
    <br>

    <% current_user.owned_friend_circles.each do |fc| %>
    <label>
      <%= fc.name %>
      <input type="checkbox" name="post[friend_circle_ids][]"
       value="<%=fc.id%>" <%= "checked" if post.friend_circles.include?(fc) %> >
    </label>
    <% end %>

    <input type="submit">
</form>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'post_form', url: posts_url(@post), post: @post, method: :put%>

app/views/posts/new.html.erb
<h1> New Post </h1>

<form action="<%=posts_url%>" method='post'>
    <input type="hidden"
            name="authenticity_token"
            value="<%= form_authenticity_token %>">

    <input type="hidden" name="post[user_id]" value="<%= current_user.id %>">

    <label>
      Body
      <textarea name="post[body]"> </textarea>
    </label>
    <br>
    <label>
      Link 1
      <input type="text" name="link[url][]">
    </label>
    <br>
    <label>
      Link 2
      <input type="text" name="link[url][]">
    </label>
    <br>
    <label>
      Link 3
      <input type="text" name="link[url][]">
    </label>
    <br>

    <% current_user.owned_friend_circles.each do |fc| %>
    <label>
      <%= fc.name %>
      <input type="checkbox" name="post[friend_circle_ids][]"
       value="<%=fc.id%>">
    </label>
    <% end %>

    <input type="submit">
</form>

app/views/posts/show.html.erb
<p>
  <%= @post.body %>
</p>

<% @post.links.each do |link| %>
  <br>
  <%= link.url %>
<% end %>

<h4>This post was shared with the following circles:</h4>

<ul>
<% @post.friend_circles.each do |fc| %>
  <li>
    <%= fc.name%>
  </li>
<% end %>
</ul>

app/views/users/edit.html.erb
<h1>Welcome <%= @user.email %></h1>
<br>
<h2>Reset your password here!</h2>

<form action="<%=user_url(@user)%>" method='post'>
  <input type='hidden' name='_method' value='put'>
  <input type='hidden'
          name='authenticity_token'
          value="<%= form_authenticity_token %>">

  <label>
    Password
    <input type='password' name='user[password]'>
  </label>

  <input type='submit'>
</form>

app/views/users/new.html.erb
<%= render "layouts/user", url: users_url %>